services:
  db:
    image: postgres:17
    container_name: smarthire_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smarthire_db
      POSTGRES_USER: smarthire_user
      POSTGRES_PASSWORD: SmartHire@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: smarthire_django
    restart: unless-stopped


    env_file:
      - .env.docker

    volumes:
      - .:/app

    expose:
      - "8000"

    depends_on:
      - db

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/')"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nginx:
    build:
      context: ./nginx
    container_name: smarthire_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - web

volumes:
  postgres_data: