# Generated by Django 6.0.7 on 2026-08-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_repair_missing_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
