# Generated by Django 6.0.7 on 2026-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
