# Generated by Django 6.0.7 on 2026-08-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0003_application_match_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('offered_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joining_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Withdrawn', 'Withdrawn')], db_index=True, default='Pending', max_length=20)),
                ('recruiter_note', models.TextField(blank=True)),
                ('candidate_note', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='applicants.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
