# Generated by Django 6.0.7 on 2026-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='employment_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full Time', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='joining_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='offer',
            name='work_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
