# Generated by Django 6.0.7 on 2026-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_note',
            field=models.TextField(blank=True, help_text="Candidate's reason when declining or requesting a reschedule."),
        ),
        migrations.AddField(
            model_name='interview',
            name='candidate_response',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Reschedule', 'Reschedule Requested')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
