# Generated by Django 6.0.7 on 2026-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_candidate_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='communication_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Communication rating out of 5', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True, help_text="Recruiter's interview feedback."),
        ),
        migrations.AddField(
            model_name='interview',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall interview rating', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='problem_solving_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Problem solving rating out of 5', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('Strong Hire', 'Strong Hire'), ('Hire', 'Hire'), ('Hold', 'Hold'), ('Reject', 'Reject')], max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='technical_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Technical rating out of 5', null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate_note',
            field=models.TextField(blank=True, help_text='Candidate reason when declining or requesting reschedule.'),
        ),
    ]
