# Generated by Django 6.0.7 on 2026-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_communication_rating_interview_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_round',
            field=models.CharField(choices=[('Screening', 'Screening'), ('Technical 1', 'Technical Round 1'), ('Technical 2', 'Technical Round 2'), ('Managerial', 'Managerial'), ('HR', 'HR'), ('Final', 'Final')], db_index=True, default='Screening', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate_note',
            field=models.TextField(blank=True, help_text='Candidate reason for declining or requesting reschedule.'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Phone', 'Phone')], db_index=True, default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='interview',
            name='problem_solving_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Problem Solving rating out of 5', null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], db_index=True, default='Scheduled', max_length=20),
        ),
    ]
